get:
    operationId: users.managedDevices.ListDeviceConfigurationStates
    parameters:
        - description: 'key: user-id of user'
          in: path
          name: user-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
        - description: 'key: managedDevice-id of managedDevice'
          in: path
          name: managedDevice-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: managedDevice
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - description: Order items by property values
          explode: false
          in: query
          name: $orderby
          schema:
            items:
                enum:
                    - id
                    - id desc
                    - displayName
                    - displayName desc
                    - platformType
                    - platformType desc
                    - settingCount
                    - settingCount desc
                    - settingStates
                    - settingStates desc
                    - state
                    - state desc
                    - version
                    - version desc
                type: string
            type: array
          style: form
        - description: Select properties to be returned
          explode: false
          in: query
          name: $select
          schema:
            items:
                enum:
                    - id
                    - displayName
                    - platformType
                    - settingCount
                    - settingStates
                    - state
                    - version
                type: string
            type: array
          style: form
        - description: Expand related entities
          explode: false
          in: query
          name: $expand
          schema:
            items:
                enum:
                    - '*'
                type: string
            type: array
          style: form
    responses:
        "200":
            content:
                application/json:
                    schema:
                        properties:
                            value:
                                items:
                                    $ref: '#/components/schemas/microsoft.graph.deviceConfigurationState'
                                type: array
                        title: Collection of deviceConfigurationState
                        type: object
            description: Retrieved navigation property
        default:
            $ref: '#/components/responses/error'
    summary: Get deviceConfigurationStates from users
    tags:
        - users.managedDevice
    x-ms-docs-operation-type: operation
post:
    operationId: users.managedDevices.CreateDeviceConfigurationStates
    parameters:
        - description: 'key: user-id of user'
          in: path
          name: user-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
        - description: 'key: managedDevice-id of managedDevice'
          in: path
          name: managedDevice-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: managedDevice
    requestBody:
        $ref: '#/components/requestBodies/microsoft.graph.deviceConfigurationState'
    responses:
        "201":
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/microsoft.graph.deviceConfigurationState'
            description: Created navigation property.
        default:
            $ref: '#/components/responses/error'
    summary: Create new navigation property to deviceConfigurationStates for users
    tags:
        - users.managedDevice
    x-ms-docs-operation-type: operation
