allOf:
    - $ref: "#/components/schemas/microsoft.graph.entity"
    - title: managedDeviceMobileAppConfigurationUserSummary
      description: Contains properties, inherited properties and actions for an MDM mobile app configuration user status summary.
      type: object
      properties:
        configurationVersion:
            format: int32
            description: Version of the policy for that overview
            maximum: 2147483647
            minimum: -2147483648
            type: integer
        errorCount:
            format: int32
            description: Number of error Users
            maximum: 2147483647
            minimum: -2147483648
            type: integer
        failedCount:
            format: int32
            description: Number of failed Users
            maximum: 2147483647
            minimum: -2147483648
            type: integer
        lastUpdateDateTime:
            format: date-time
            description: Last update time
            pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
            type: string
        notApplicableCount:
            format: int32
            description: Number of not applicable users
            maximum: 2147483647
            minimum: -2147483648
            type: integer
        pendingCount:
            format: int32
            description: Number of pending Users
            maximum: 2147483647
            minimum: -2147483648
            type: integer
        successCount:
            format: int32
            description: Number of succeeded Users
            maximum: 2147483647
            minimum: -2147483648
            type: integer
example:
    id: string (identifier)
    configurationVersion: integer
    errorCount: integer
    failedCount: integer
    lastUpdateDateTime: string (timestamp)
    notApplicableCount: integer
    pendingCount: integer
    successCount: integer
