allOf:
    - $ref: "#/components/schemas/microsoft.graph.entity"
    - title: managedDeviceMobileAppConfigurationDeviceStatus
      description: Contains properties, inherited properties and actions for an MDM mobile app configuration status for a device.
      type: object
      properties:
        complianceGracePeriodExpirationDateTime:
            format: date-time
            description: The DateTime when device compliance grace period expires
            pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
            type: string
        deviceDisplayName:
            description: Device name of the DevicePolicyStatus.
            type: string
        deviceModel:
            description: The device model that is being reported
            type: string
        lastReportedDateTime:
            format: date-time
            description: Last modified date time of the policy report.
            pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
            type: string
        status:
            description: Compliance status of the policy report.
        userName:
            description: The User Name that is being reported
            type: string
        userPrincipalName:
            description: UserPrincipalName.
            type: string
example:
    id: string (identifier)
    complianceGracePeriodExpirationDateTime: string (timestamp)
    deviceDisplayName: string
    deviceModel: string
    lastReportedDateTime: string (timestamp)
    status:
        "@odata.type": microsoft.graph.complianceStatus
    userName: string
    userPrincipalName: string
