allOf:
    - $ref: "#/components/schemas/microsoft.graph.entity"
    - title: managedDeviceMobileAppConfigurationUserStatus
      description: Contains properties, inherited properties and actions for an MDM mobile app configuration status for a user.
      type: object
      properties:
        devicesCount:
            format: int32
            description: Devices count for that user.
            maximum: 2147483647
            minimum: -2147483648
            type: integer
        lastReportedDateTime:
            format: date-time
            description: Last modified date time of the policy report.
            pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
            type: string
        status:
            description: Compliance status of the policy report.
        userDisplayName:
            description: User name of the DevicePolicyStatus.
            type: string
        userPrincipalName:
            description: UserPrincipalName.
            type: string
example:
    id: string (identifier)
    devicesCount: integer
    lastReportedDateTime: string (timestamp)
    status:
        "@odata.type": microsoft.graph.complianceStatus
    userDisplayName: string
    userPrincipalName: string
