allOf:
    - $ref: "#/components/schemas/microsoft.graph.entity"
    - title: workbookApplication
      type: object
      properties:
        calculationMode:
            type: string
example:
    id: string (identifier)
    calculationMode: string
