allOf:
    - $ref: "#/components/schemas/microsoft.graph.entity"
    - title: deviceConfigurationDeviceStateSummary
      type: object
      properties:
        compliantDeviceCount:
            format: int32
            description: Number of compliant devices
            maximum: 2147483647
            minimum: -2147483648
            type: integer
        conflictDeviceCount:
            format: int32
            description: Number of conflict devices
            maximum: 2147483647
            minimum: -2147483648
            type: integer
        errorDeviceCount:
            format: int32
            description: Number of error devices
            maximum: 2147483647
            minimum: -2147483648
            type: integer
        nonCompliantDeviceCount:
            format: int32
            description: Number of NonCompliant devices
            maximum: 2147483647
            minimum: -2147483648
            type: integer
        notApplicableDeviceCount:
            format: int32
            description: Number of not applicable devices
            maximum: 2147483647
            minimum: -2147483648
            type: integer
        remediatedDeviceCount:
            format: int32
            description: Number of remediated devices
            maximum: 2147483647
            minimum: -2147483648
            type: integer
        unknownDeviceCount:
            format: int32
            description: Number of unknown devices
            maximum: 2147483647
            minimum: -2147483648
            type: integer
example:
    id: string (identifier)
    compliantDeviceCount: integer
    conflictDeviceCount: integer
    errorDeviceCount: integer
    nonCompliantDeviceCount: integer
    notApplicableDeviceCount: integer
    remediatedDeviceCount: integer
    unknownDeviceCount: integer
