allOf:
    - $ref: "#/components/schemas/microsoft.graph.entity"
    - title: deviceEnrollmentConfiguration
      description: The Base Class of Device Enrollment Configuration
      type: object
      properties:
        createdDateTime:
            format: date-time
            description: Created date time in UTC of the device enrollment configuration
            pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
            type: string
        description:
            description: The description of the device enrollment configuration
            type: string
        displayName:
            description: The display name of the device enrollment configuration
            type: string
        lastModifiedDateTime:
            format: date-time
            description: Last modified date time in UTC of the device enrollment configuration
            pattern: ^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$
            type: string
        priority:
            format: int32
            description: Priority is used when a user exists in multiple groups that are assigned enrollment configuration. Users are subject only to the configuration with the lowest priority value.
            maximum: 2147483647
            minimum: -2147483648
            type: integer
        version:
            format: int32
            description: The version of the device enrollment configuration
            maximum: 2147483647
            minimum: -2147483648
            type: integer
        assignments:
            type: array
            items:
                $ref: "#/components/schemas/microsoft.graph.enrollmentConfigurationAssignment"
example:
    id: string (identifier)
    createdDateTime: string (timestamp)
    description: string
    displayName: string
    lastModifiedDateTime: string (timestamp)
    priority: integer
    version: integer
    assignments:
        - "@odata.type": microsoft.graph.enrollmentConfigurationAssignment
