get:
    operationId: deviceManagement.GetDeviceCompliancePolicySettingStateSummaries
    parameters:
        - description: 'key: deviceCompliancePolicySettingStateSummary-id of deviceCompliancePolicySettingStateSummary'
          in: path
          name: deviceCompliancePolicySettingStateSummary-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: deviceCompliancePolicySettingStateSummary
        - description: Select properties to be returned
          explode: false
          in: query
          name: $select
          schema:
            items:
                enum:
                    - id
                    - compliantDeviceCount
                    - conflictDeviceCount
                    - errorDeviceCount
                    - nonCompliantDeviceCount
                    - notApplicableDeviceCount
                    - platformType
                    - remediatedDeviceCount
                    - setting
                    - settingName
                    - unknownDeviceCount
                    - deviceComplianceSettingStates
                type: string
            type: array
          style: form
        - description: Expand related entities
          explode: false
          in: query
          name: $expand
          schema:
            items:
                enum:
                    - '*'
                    - deviceComplianceSettingStates
                type: string
            type: array
          style: form
    responses:
        "200":
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/microsoft.graph.deviceCompliancePolicySettingStateSummary'
            description: Retrieved navigation property
        default:
            $ref: '#/components/responses/error'
    summary: Get deviceCompliancePolicySettingStateSummaries from deviceManagement
    tags:
        - deviceManagement.deviceCompliancePolicySettingStateSummary
    x-ms-docs-operation-type: operation
patch:
    operationId: deviceManagement.UpdateDeviceCompliancePolicySettingStateSummaries
    parameters:
        - description: 'key: deviceCompliancePolicySettingStateSummary-id of deviceCompliancePolicySettingStateSummary'
          in: path
          name: deviceCompliancePolicySettingStateSummary-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: deviceCompliancePolicySettingStateSummary
    requestBody:
        content:
            application/json:
                schema:
                    $ref: '#/components/schemas/microsoft.graph.deviceCompliancePolicySettingStateSummary'
        description: New navigation property values
        required: true
    responses:
        "204":
            description: Success
        default:
            $ref: '#/components/responses/error'
    summary: Update the navigation property deviceCompliancePolicySettingStateSummaries in deviceManagement
    tags:
        - deviceManagement.deviceCompliancePolicySettingStateSummary
    x-ms-docs-operation-type: operation
