get:
    operationId: shares.GetSite
    parameters:
        - description: 'key: sharedDriveItem-id of sharedDriveItem'
          in: path
          name: sharedDriveItem-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: sharedDriveItem
        - description: Select properties to be returned
          explode: false
          in: query
          name: $select
          schema:
            items:
                enum:
                    - id
                    - createdBy
                    - createdDateTime
                    - description
                    - eTag
                    - lastModifiedBy
                    - lastModifiedDateTime
                    - name
                    - parentReference
                    - webUrl
                    - displayName
                    - error
                    - root
                    - sharepointIds
                    - siteCollection
                    - createdByUser
                    - lastModifiedByUser
                    - analytics
                    - columns
                    - contentTypes
                    - drive
                    - drives
                    - items
                    - lists
                    - sites
                    - onenote
                type: string
            type: array
          style: form
        - description: Expand related entities
          explode: false
          in: query
          name: $expand
          schema:
            items:
                enum:
                    - '*'
                    - createdByUser
                    - lastModifiedByUser
                    - analytics
                    - columns
                    - contentTypes
                    - drive
                    - drives
                    - items
                    - lists
                    - sites
                    - onenote
                type: string
            type: array
          style: form
    responses:
        "200":
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/microsoft.graph.site'
            description: Retrieved navigation property
        default:
            $ref: '#/components/responses/error'
    summary: Get site from shares
    tags:
        - shares.site
    x-ms-docs-operation-type: operation
patch:
    operationId: shares.UpdateSite
    parameters:
        - description: 'key: sharedDriveItem-id of sharedDriveItem'
          in: path
          name: sharedDriveItem-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: sharedDriveItem
    requestBody:
        $ref: '#/components/requestBodies/microsoft.graph.site'
    responses:
        "204":
            description: Success
        default:
            $ref: '#/components/responses/error'
    summary: Update the navigation property site in shares
    tags:
        - shares.site
    x-ms-docs-operation-type: operation
