delete:
    operationId: applications.application.DeleteApplication
    parameters:
        - description: 'key: application-id of application'
          in: path
          name: application-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: application
        - description: ETag
          in: header
          name: If-Match
          schema:
            type: string
    responses:
        "204":
            description: Success
        default:
            $ref: '#/components/responses/error'
    summary: Delete entity from applications
    tags:
        - applications.application
    x-ms-docs-operation-type: operation
get:
    operationId: applications.application.GetApplication
    parameters:
        - description: 'key: application-id of application'
          in: path
          name: application-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: application
        - description: Select properties to be returned
          explode: false
          in: query
          name: $select
          schema:
            items:
                enum:
                    - id
                    - deletedDateTime
                    - addIns
                    - api
                    - appId
                    - applicationTemplateId
                    - appRoles
                    - createdDateTime
                    - description
                    - displayName
                    - groupMembershipClaims
                    - identifierUris
                    - info
                    - isDeviceOnlyAuthSupported
                    - isFallbackPublicClient
                    - keyCredentials
                    - logo
                    - notes
                    - oauth2RequirePostResponse
                    - optionalClaims
                    - parentalControlSettings
                    - passwordCredentials
                    - publicClient
                    - publisherDomain
                    - requiredResourceAccess
                    - signInAudience
                    - tags
                    - tokenEncryptionKeyId
                    - web
                    - createdOnBehalfOf
                    - extensionProperties
                    - homeRealmDiscoveryPolicies
                    - owners
                    - tokenIssuancePolicies
                    - tokenLifetimePolicies
                type: string
            type: array
          style: form
    responses:
        "200":
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/microsoft.graph.application'
            description: Retrieved entity
        default:
            $ref: '#/components/responses/error'
    summary: Get entity from applications by key
    tags:
        - applications.application
    x-ms-docs-operation-type: operation
patch:
    operationId: applications.application.UpdateApplication
    parameters:
        - description: 'key: application-id of application'
          in: path
          name: application-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: application
    requestBody:
        content:
            application/json:
                schema:
                    $ref: '#/components/schemas/microsoft.graph.application'
        description: New property values
        required: true
    responses:
        "204":
            description: Success
        default:
            $ref: '#/components/responses/error'
    summary: Update entity in applications
    tags:
        - applications.application
    x-ms-docs-operation-type: operation
