get:
    operationId: workbooks.workbook.worksheets.GetCharts
    parameters:
        - description: 'key: driveItem-id of driveItem'
          in: path
          name: driveItem-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: driveItem
        - description: 'key: workbookWorksheet-id of workbookWorksheet'
          in: path
          name: workbookWorksheet-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: workbookWorksheet
        - description: 'key: workbookChart-id of workbookChart'
          in: path
          name: workbookChart-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: workbookChart
        - description: Select properties to be returned
          explode: false
          in: query
          name: $select
          schema:
            items:
                enum:
                    - id
                    - height
                    - left
                    - name
                    - top
                    - width
                    - axes
                    - dataLabels
                    - format
                    - legend
                    - series
                    - title
                    - worksheet
                type: string
            type: array
          style: form
        - description: Expand related entities
          explode: false
          in: query
          name: $expand
          schema:
            items:
                enum:
                    - '*'
                    - axes
                    - dataLabels
                    - format
                    - legend
                    - series
                    - title
                    - worksheet
                type: string
            type: array
          style: form
    responses:
        "200":
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/microsoft.graph.workbookChart'
            description: Retrieved navigation property
        default:
            $ref: '#/components/responses/error'
    summary: Get charts from workbooks
    tags:
        - workbooks.workbook
    x-ms-docs-operation-type: operation
patch:
    operationId: workbooks.workbook.worksheets.UpdateCharts
    parameters:
        - description: 'key: driveItem-id of driveItem'
          in: path
          name: driveItem-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: driveItem
        - description: 'key: workbookWorksheet-id of workbookWorksheet'
          in: path
          name: workbookWorksheet-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: workbookWorksheet
        - description: 'key: workbookChart-id of workbookChart'
          in: path
          name: workbookChart-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: workbookChart
    requestBody:
        $ref: '#/components/requestBodies/microsoft.graph.workbookChart'
    responses:
        "204":
            description: Success
        default:
            $ref: '#/components/responses/error'
    summary: Update the navigation property charts in workbooks
    tags:
        - workbooks.workbook
    x-ms-docs-operation-type: operation
