get:
    operationId: deviceManagement.deviceConfigurations.GetAssignments
    parameters:
        - description: 'key: deviceConfiguration-id of deviceConfiguration'
          in: path
          name: deviceConfiguration-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: deviceConfiguration
        - description: 'key: deviceConfigurationAssignment-id of deviceConfigurationAssignment'
          in: path
          name: deviceConfigurationAssignment-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: deviceConfigurationAssignment
        - description: Select properties to be returned
          explode: false
          in: query
          name: $select
          schema:
            items:
                enum:
                    - id
                    - target
                type: string
            type: array
          style: form
        - description: Expand related entities
          explode: false
          in: query
          name: $expand
          schema:
            items:
                enum:
                    - '*'
                type: string
            type: array
          style: form
    responses:
        "200":
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/microsoft.graph.deviceConfigurationAssignment'
            description: Retrieved navigation property
        default:
            $ref: '#/components/responses/error'
    summary: Get assignments from deviceManagement
    tags:
        - deviceManagement.deviceConfiguration
    x-ms-docs-operation-type: operation
patch:
    operationId: deviceManagement.deviceConfigurations.UpdateAssignments
    parameters:
        - description: 'key: deviceConfiguration-id of deviceConfiguration'
          in: path
          name: deviceConfiguration-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: deviceConfiguration
        - description: 'key: deviceConfigurationAssignment-id of deviceConfigurationAssignment'
          in: path
          name: deviceConfigurationAssignment-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: deviceConfigurationAssignment
    requestBody:
        content:
            application/json:
                schema:
                    $ref: '#/components/schemas/microsoft.graph.deviceConfigurationAssignment'
        description: New navigation property values
        required: true
    responses:
        "204":
            description: Success
        default:
            $ref: '#/components/responses/error'
    summary: Update the navigation property assignments in deviceManagement
    tags:
        - deviceManagement.deviceConfiguration
    x-ms-docs-operation-type: operation
