get:
    operationId: deviceManagement.GetConditionalAccessSettings
    parameters:
        - description: Select properties to be returned
          explode: false
          in: query
          name: $select
          schema:
            items:
                enum:
                    - id
                    - enabled
                    - excludedGroups
                    - includedGroups
                    - overrideDefaultRule
                type: string
            type: array
          style: form
        - description: Expand related entities
          explode: false
          in: query
          name: $expand
          schema:
            items:
                enum:
                    - '*'
                type: string
            type: array
          style: form
    responses:
        "200":
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/microsoft.graph.onPremisesConditionalAccessSettings'
            description: Retrieved navigation property
        default:
            $ref: '#/components/responses/error'
    summary: Get conditionalAccessSettings from deviceManagement
    tags:
        - deviceManagement.onPremisesConditionalAccessSettings
    x-ms-docs-operation-type: operation
patch:
    operationId: deviceManagement.UpdateConditionalAccessSettings
    requestBody:
        content:
            application/json:
                schema:
                    $ref: '#/components/schemas/microsoft.graph.onPremisesConditionalAccessSettings'
        description: New navigation property values
        required: true
    responses:
        "204":
            description: Success
        default:
            $ref: '#/components/responses/error'
    summary: Update the navigation property conditionalAccessSettings in deviceManagement
    tags:
        - deviceManagement.onPremisesConditionalAccessSettings
    x-ms-docs-operation-type: operation
