get:
    operationId: deviceManagement.ListDeviceCompliancePolicySettingStateSummaries
    parameters:
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - description: Order items by property values
          explode: false
          in: query
          name: $orderby
          schema:
            items:
                enum:
                    - id
                    - id desc
                    - compliantDeviceCount
                    - compliantDeviceCount desc
                    - conflictDeviceCount
                    - conflictDeviceCount desc
                    - errorDeviceCount
                    - errorDeviceCount desc
                    - nonCompliantDeviceCount
                    - nonCompliantDeviceCount desc
                    - notApplicableDeviceCount
                    - notApplicableDeviceCount desc
                    - platformType
                    - platformType desc
                    - remediatedDeviceCount
                    - remediatedDeviceCount desc
                    - setting
                    - setting desc
                    - settingName
                    - settingName desc
                    - unknownDeviceCount
                    - unknownDeviceCount desc
                type: string
            type: array
          style: form
        - description: Select properties to be returned
          explode: false
          in: query
          name: $select
          schema:
            items:
                enum:
                    - id
                    - compliantDeviceCount
                    - conflictDeviceCount
                    - errorDeviceCount
                    - nonCompliantDeviceCount
                    - notApplicableDeviceCount
                    - platformType
                    - remediatedDeviceCount
                    - setting
                    - settingName
                    - unknownDeviceCount
                    - deviceComplianceSettingStates
                type: string
            type: array
          style: form
        - description: Expand related entities
          explode: false
          in: query
          name: $expand
          schema:
            items:
                enum:
                    - '*'
                    - deviceComplianceSettingStates
                type: string
            type: array
          style: form
    responses:
        "200":
            content:
                application/json:
                    schema:
                        properties:
                            value:
                                items:
                                    $ref: '#/components/schemas/microsoft.graph.deviceCompliancePolicySettingStateSummary'
                                type: array
                        title: Collection of deviceCompliancePolicySettingStateSummary
                        type: object
            description: Retrieved navigation property
        default:
            $ref: '#/components/responses/error'
    summary: Get deviceCompliancePolicySettingStateSummaries from deviceManagement
    tags:
        - deviceManagement.deviceCompliancePolicySettingStateSummary
    x-ms-docs-operation-type: operation
post:
    operationId: deviceManagement.CreateDeviceCompliancePolicySettingStateSummaries
    requestBody:
        content:
            application/json:
                schema:
                    $ref: '#/components/schemas/microsoft.graph.deviceCompliancePolicySettingStateSummary'
        description: New navigation property
        required: true
    responses:
        "201":
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/microsoft.graph.deviceCompliancePolicySettingStateSummary'
            description: Created navigation property.
        default:
            $ref: '#/components/responses/error'
    summary: Create new navigation property to deviceCompliancePolicySettingStateSummaries for deviceManagement
    tags:
        - deviceManagement.deviceCompliancePolicySettingStateSummary
    x-ms-docs-operation-type: operation
