get:
    operationId: deviceAppManagement.mobileAppConfigurations.GetUserStatuses
    parameters:
        - description: 'key: managedDeviceMobileAppConfiguration-id of managedDeviceMobileAppConfiguration'
          in: path
          name: managedDeviceMobileAppConfiguration-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: managedDeviceMobileAppConfiguration
        - description: 'key: managedDeviceMobileAppConfigurationUserStatus-id of managedDeviceMobileAppConfigurationUserStatus'
          in: path
          name: managedDeviceMobileAppConfigurationUserStatus-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: managedDeviceMobileAppConfigurationUserStatus
        - description: Select properties to be returned
          explode: false
          in: query
          name: $select
          schema:
            items:
                enum:
                    - id
                    - devicesCount
                    - lastReportedDateTime
                    - status
                    - userDisplayName
                    - userPrincipalName
                type: string
            type: array
          style: form
        - description: Expand related entities
          explode: false
          in: query
          name: $expand
          schema:
            items:
                enum:
                    - '*'
                type: string
            type: array
          style: form
    responses:
        "200":
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/microsoft.graph.managedDeviceMobileAppConfigurationUserStatus'
            description: Retrieved navigation property
        default:
            $ref: '#/components/responses/error'
    summary: Get userStatuses from deviceAppManagement
    tags:
        - deviceAppManagement.managedDeviceMobileAppConfiguration
    x-ms-docs-operation-type: operation
patch:
    operationId: deviceAppManagement.mobileAppConfigurations.UpdateUserStatuses
    parameters:
        - description: 'key: managedDeviceMobileAppConfiguration-id of managedDeviceMobileAppConfiguration'
          in: path
          name: managedDeviceMobileAppConfiguration-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: managedDeviceMobileAppConfiguration
        - description: 'key: managedDeviceMobileAppConfigurationUserStatus-id of managedDeviceMobileAppConfigurationUserStatus'
          in: path
          name: managedDeviceMobileAppConfigurationUserStatus-id
          required: true
          schema:
            type: string
          x-ms-docs-key-type: managedDeviceMobileAppConfigurationUserStatus
    requestBody:
        content:
            application/json:
                schema:
                    $ref: '#/components/schemas/microsoft.graph.managedDeviceMobileAppConfigurationUserStatus'
        description: New navigation property values
        required: true
    responses:
        "204":
            description: Success
        default:
            $ref: '#/components/responses/error'
    summary: Update the navigation property userStatuses in deviceAppManagement
    tags:
        - deviceAppManagement.managedDeviceMobileAppConfiguration
    x-ms-docs-operation-type: operation
