content:
    application/json:
        schema:
            type: object
            properties:
                keyId:
                    format: uuid
                    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
                    type: string
description: Action parameters
required: true
