content:
    application/json:
        schema:
            type: object
            properties:
                assignments:
                    type: array
                    items: {}
description: Action parameters
required: true
