get:
    operationId: reports.deviceConfigurationDeviceActivity
    responses:
        "200":
            content:
                application/json:
                    schema: {}
            description: Success
        default:
            $ref: '#/components/responses/error'
    summary: Invoke function deviceConfigurationDeviceActivity
    tags:
        - reports.Functions
    x-ms-docs-operation-type: function
