get:
    operationId: deviceAppManagement.ListTargetedManagedAppConfigurations
    parameters:
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - description: Order items by property values
          explode: false
          in: query
          name: $orderby
          schema:
            items:
                enum:
                    - id
                    - id desc
                    - createdDateTime
                    - createdDateTime desc
                    - description
                    - description desc
                    - displayName
                    - displayName desc
                    - lastModifiedDateTime
                    - lastModifiedDateTime desc
                    - version
                    - version desc
                    - customSettings
                    - customSettings desc
                    - deployedAppCount
                    - deployedAppCount desc
                    - isAssigned
                    - isAssigned desc
                type: string
            type: array
          style: form
        - description: Select properties to be returned
          explode: false
          in: query
          name: $select
          schema:
            items:
                enum:
                    - id
                    - createdDateTime
                    - description
                    - displayName
                    - lastModifiedDateTime
                    - version
                    - customSettings
                    - deployedAppCount
                    - isAssigned
                    - apps
                    - assignments
                    - deploymentSummary
                type: string
            type: array
          style: form
        - description: Expand related entities
          explode: false
          in: query
          name: $expand
          schema:
            items:
                enum:
                    - '*'
                    - apps
                    - assignments
                    - deploymentSummary
                type: string
            type: array
          style: form
    responses:
        "200":
            content:
                application/json:
                    schema:
                        properties:
                            value:
                                items:
                                    $ref: '#/components/schemas/microsoft.graph.targetedManagedAppConfiguration'
                                type: array
                        title: Collection of targetedManagedAppConfiguration
                        type: object
            description: Retrieved navigation property
        default:
            $ref: '#/components/responses/error'
    summary: Get targetedManagedAppConfigurations from deviceAppManagement
    tags:
        - deviceAppManagement.targetedManagedAppConfiguration
    x-ms-docs-operation-type: operation
post:
    operationId: deviceAppManagement.CreateTargetedManagedAppConfigurations
    requestBody:
        content:
            application/json:
                schema:
                    $ref: '#/components/schemas/microsoft.graph.targetedManagedAppConfiguration'
        description: New navigation property
        required: true
    responses:
        "201":
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/microsoft.graph.targetedManagedAppConfiguration'
            description: Created navigation property.
        default:
            $ref: '#/components/responses/error'
    summary: Create new navigation property to targetedManagedAppConfigurations for deviceAppManagement
    tags:
        - deviceAppManagement.targetedManagedAppConfiguration
    x-ms-docs-operation-type: operation
