# Checks for an update to the schema. If one exists, update our repo

name: Continious Intigration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    outputs: 
      diff: ${{ steps.git-diff.outputs.diff }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Environment
        run: npm install

      - name: Download v1 Swagger 2.0 Definition
        run: wget -O src/v1/swagger.yaml "https://graphslice.azurewebsites.net/openapi?operationIds=*&openApiVersion=2&graphVersion=v1.0"

      - name: Download beta Swagger 2.0 Definition
        run: wget -O src/beta/swagger.yaml "https://graphslice.azurewebsites.net/openapi?operationIds=*&openApiVersion=2&graphVersion=beta"

      - name: Convert v1 Swagger 2.0 to OpenAPI 3.0 Definition
        run: ./node_modules/.bin/swagger2openapi -p -o src/v1/openapi.yaml src/v1/swagger.yaml

      - name: Convert beta Swagger 2.0 to OpenAPI 3.0 Definition
        run: ./node_modules/.bin/swagger2openapi -p -o src/beta/openapi.yaml src/beta/swagger.yaml

      - name: Check Diff
        id: git-diff
        run: |
          git diff --name-only src/**/*.yaml
          echo "::set-output name=diff::$( git diff --name-only src/**/*.yaml )"
        #uses: technote-space/get-diff-action@gh-actions
        #with:
        #  PATTERNS: |
        #    src/**/*.yaml

  update:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2

      - name: Verify Diff Variable
        run: echo ${{ needs.check.outputs.diff }}

      - name: Commit Changes
        if: needs.check.outputs.diff
        run: |
          branch="release-$(uuidgen)"
          git config --global user.email "support@dalinwilliams.com"
          git config --global user.name "Support"
          echo "MADE IT HERE $bramch"
          echo $(git diff)
          git checkout -b $branch
          echo "status"
          git status
          echo "MADE IT HERE"
          git add ./src/**/*.yaml
          echo "MADE IT THERE"
          git commit -m "updating openapi and swagger files"
          echo "Almost Done"
          git push -u origin $branch
